# Generated by Django 5.2.6 on 2025-10-17 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Photo',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
